### ISSUE TITLE
Readme file

### ISSUE THREAD

**Issue by PeterSuly** [duckwc/ECAMpy#1]
Hi @duckwc ,
can you please provide readme description how to try your tool? When i run `webserver.py` i am asked to provide callback url and then i get this exception. I'm not experienced python user but would love to try this utility.

```python
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/petersuly/Downloads/ECAMpy-main/webserver.py", line 358, in <module>
    lankey = get_lankey(access_token)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/petersuly/Downloads/ECAMpy-main/webserver.py", line 169, in get_lankey
    response = requests.get(api_url, headers=headers).json()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
```

**Comment by duckwc** [comment]
Hi @PeterSuly , the python script should display a sign in URL.
When you follow the sign-in procedure, successfully, you should be redirected to a google.it page.
The URL of that google page contains a code required to complete the authentication process.
Simply copy the complete URL and paste it on the script.
This should be done only once.

**Comment by PeterSuly** [comment]
Thanks @duckwc for response. Yes, i am redirected to G page, i copy it into terminal, i get json with auth token, refresh token, coffee maker online status etc. and than error from first post happens.

**Comment by duckwc** [comment]
@PeterSuly. It looks like you don't get a json answer. 
I added some debug info in the script. 
Could you run it and let me know the result. Be sure to obfuscate your local lan key.

**Comment by duckwc** [comment]
Here is what you should get:
>lankey: {'Date': 'Mon, 26 Feb 2024 08:15:59 GMT', 'Content-Type': 'application/json;charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Content-Security-Policy': "frame-ancestors 'none'", 'ETag': '"6584f92faffb1820d0b9fbda41cbbf9f"', 'Last-Modified': 'Wed, 14 Dec 2050 18:43:58 GMT', 'Status': '200 OK', 'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'X-Rack-Cache': 'miss', 'X-Request-Id': '45d4e7a0-d47f-11ee-809f-27d85d3ce157', 'X-Runtime': '0.043389', 'X-UA-Compatible': 'IE=Edge,chrome=1', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Methods': 'GET,PUT,POST,DELETE,PATCH,OPTIONS', 'Access-Control-Allow-Headers': 'accept,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,x-csrf-token,Content-Disposition,X-Pingother', 'Access-Control-Max-Age': '1728000'} {"connection_priority":["LAN"],"auto_sync":true,"keep_alive":30,"lifetime":155522220,"local_key_id":2xxx3,"local_key":"QxxxxxxxxxxxxxxxxxxxxxxxxxxxxxA=="}

**Comment by PeterSuly** [comment]
@duckwc  This is everything what i get in terminal when i run script. XXXXXXXX strings are obfuscated.
I think the last section with local_key is missing.

```python
{'access_token': 'XXXXXXXX', 'expires_in': 86399, 'refresh_token': 'XXXXXXXX', 'role': 'EndUser', 'role_tags': []}
{'product_name': 'XXXXXXXX', 'model': 'XXXXXXXX', 'dsn': 'XXXXXXXX', 'oem_model': 'DL-striker-cb', 'sw_version': 'ADA 1.6 esp-idf-v3.3.1 2020-05-20 21:37:21 667ab48', 'template_id': 27189, 'mac': 'XXXXXXXX', 'unique_hardware_id': None, 'lan_ip': 'XXXXXXXX', 'connected_at': '2024-02-23T13:37:01Z', 'key': XXXXXXXX, 'lan_enabled': False, 'connection_priority': [], 'has_properties': True, 'product_class': None, 'connection_status': 'Online', 'lat': 'XXXXXXXX', 'lng': 'XXXXXXXX', 'locality': 'XXXXXXXX', 'device_type': 'Wifi', 'dealer': None}
lankey: {'Date': 'Mon, 26 Feb 2024 08:58:54 GMT', 'Content-Type': 'application/json;charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Content-Security-Policy': "frame-ancestors 'none'", 'Error': 'Unavailable', 'Last-Modified': 'Wed, 14 Dec 2050 18:43:58 GMT', 'Status': '404 Not Found', 'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'X-Rack-Cache': 'miss', 'X-Request-Id': '450d9140-d485-11ee-b806-19055f4ed230', 'X-Runtime': '0.030964', 'X-UA-Compatible': 'IE=Edge,chrome=1', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Methods': 'GET,PUT,POST,DELETE,PATCH,OPTIONS', 'Access-Control-Allow-Headers': 'accept,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,x-csrf-token,Content-Disposition,X-Pingother', 'Access-Control-Max-Age': '1728000'}  
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/XXXXXXXX/ECAMpy-main 2/webserver.py", line 360, in <module>
    lankey = get_lankey(access_token)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXXXXXXX/ECAMpy-main 2/webserver.py", line 171, in get_lankey
    response = data.json()
               ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
```

**Comment by duckwc** [comment]
Looks like you have  'lan_enabled': False in your model description.
Did you enroll your machine correctly with the delonghi cloud?
I haven't tried working on a complete offline system yet.

**Comment by PeterSuly** [comment]
My delonghi machine is operable through CoffeeLink app so yes, i think. 
It's okay i will try in future 👍  Thanks for great job. Closing this issue as readme file was added.
